# Generated by Django 2.2 on 2020-02-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
