# Generated by Django 2.2 on 2020-02-03 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0002_auto_20200202_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='inputtime',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 0, 32, 9, 102802, tzinfo=utc), verbose_name='input date'),
            preserve_default=False,
        ),
    ]
