# Generated by Django 2.2 on 2020-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0006_filling_gp_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='inputtime',
        ),
        migrations.AlterField(
            model_name='filling',
            name='factory',
            field=models.CharField(default='宣城百纳', max_length=32),
        ),
        migrations.AlterField(
            model_name='filling',
            name='fill_t',
            field=models.DateField(verbose_name='fill_t'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='zn_code',
            field=models.CharField(default='WR23-', max_length=32),
        ),
        migrations.AlterField(
            model_name='gp',
            name='manufacturer',
            field=models.CharField(default='宣城市百纳压力容器制造有限公司', max_length=100),
        ),
        migrations.AlterField(
            model_name='gp',
            name='zn_code',
            field=models.CharField(default='WR23-', max_length=32),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(default='陵阳镇', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateField(verbose_name='input date'),
        ),
    ]
