# Generated by Django 2.2 on 2020-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0007_auto_20200203_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='remark',
            field=models.TextField(default='说明'),
        ),
        migrations.AlterField(
            model_name='gp',
            name='remark',
            field=models.TextField(default='说明'),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.TextField(default='说明'),
        ),
    ]
