# Generated by Django 2.2 on 2020-02-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0008_auto_20200204_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
