# Generated by Django 2.2 on 2020-02-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0009_auto_20200204_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gp_code',
            field=models.CharField(default='000000', max_length=32, verbose_name='钢瓶编号'),
        ),
    ]
