# Generated by Django 2.2 on 2020-02-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0011_auto_20200204_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
