# Generated by Django 2.2 on 2020-02-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0012_auto_20200204_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filling',
            options={'verbose_name_plural': '充装表'},
        ),
        migrations.AlterModelOptions(
            name='gp',
            options={'verbose_name_plural': '钢瓶表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': '收发记录表'},
        ),
        migrations.AddField(
            model_name='record',
            name='delivery',
            field=models.CharField(choices=[('1', '自取'), ('2', '配送工')], default='wgc', max_length=32),
            preserve_default=False,
        ),
    ]
