# Generated by Django 2.2 on 2020-02-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0013_auto_20200204_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='delivery',
            field=models.CharField(default='自取', max_length=32, verbose_name='配送员'),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
