# Generated by Django 2.2 on 2020-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0014_auto_20200204_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp',
            name='gp_code',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='钢瓶编号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='delivery',
            field=models.CharField(default='站点自取', max_length=32, verbose_name='配送员'),
        ),
    ]
