# Generated by Django 2.2 on 2020-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0015_auto_20200204_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp',
            name='gp_code',
            field=models.CharField(default='000000', max_length=32, verbose_name='钢瓶编号'),
        ),
    ]
